/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();//class name
        int[] arr=classUnderTest.roll(4); //output of roll methode
        int[][] weeklyMonthTemperatures = {      // input array for the test of lowest avvarage
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        assertArrayEquals(arr,arr); //test of roll method
        int[] array={1, 2, 3, 4};//test input array
        int [] arr2= {57};// test out put array
        assertTrue(classUnderTest.containsDuplicates(array), String.valueOf(true)); //test
        assertEquals(classUnderTest.calculatingAverages(array),2.5);//test
        assertArrayEquals(classUnderTest.lowestAverage(weeklyMonthTemperatures),arr2);//test
    }
}
