/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Library {
    public static void main(String[] args) {
        Theater testShop= new Theater("Thater1");
        testShop.addMovie("pat man");
        testShop.addMovie("spider man");
        testShop.addMovie("new man");
        testShop.addRevews("wael",4,"good");
       System.out.println(testShop.toString());
    }

}

