/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
Restaurant Res1=new Restaurant("res1","$");
Res1.addRevews("wael",2);
        Res1.addRevews("wael",4);
        Res1.addRevews("wael",3);

        Res1.addRevews("wael",3);
Res1.getReview();
    }

}

