/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.io.*;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        fileJsTester("resources/gates.js");
    }

    public static int  fileJsTester(String phth) {
        int errorCounter=0;
        File file = new File(phth); // will be relative to the root of the project
        try (Scanner scanner = new Scanner(file)) {
            int counter=0;

            while (scanner.hasNextLine()) {
                String line=scanner.nextLine();
                counter++;
                if(line.contains(";")|| line.isEmpty() || line.contains("{") || line.contains("}")  || line.contains("if") || line.contains("else"))   {

                }
                else {  errorCounter++;
                    System.out.println("Line "+counter+": Missing semicolon");}

            }

        } catch (FileNotFoundException fileNotFoundException) {

            System.err.println(fileNotFoundException.getMessage());


        }
        //        File file1 = new File("/home/jason/Desktop/class-names.txt"); // absolute paths
        System.out.println("NUM "+errorCounter+": Missing semicolon");
        return errorCounter;
    }

}
