/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @DisplayName("Restorant Test")
    @Test void testRestorant() {
        Restaurant classUnderTest = new Restaurant("restName","$");
        assertEquals("restName",classUnderTest.getName());
        assertEquals(classUnderTest.toString(),"Restaurant{name='restName', stars=5, price=$}");

    }
    @DisplayName("Review Test")
    @Test void testReview(){
        Review classUndertest= new Review("wael",5);
        assertEquals(classUndertest.toString(),"Review{author='wael', authorReviw=5}");
    }

    @DisplayName(" add Review to the restorant test")
    @Test void testAddReviewToRestorant(){
        Restaurant testRest= new Restaurant("Rest1","$");
        testRest.addRevews("wael",4);
        assertEquals(testRest.toString(),"Restaurant{name='Rest1', stars=4, price=$}");
    }

    @DisplayName(" add  multi Review to the restorant test")
    @Test void testAddMultiReviewToRestorant(){
        Restaurant testRest= new Restaurant("Rest1","$");
        testRest.addRevews("wae2",4);
        testRest.addRevews("wae2l",4);
        testRest.addRevews("wae2l",2);
        testRest.addRevews("wae2l",2);
        assertEquals(testRest.toString(),"Restaurant{name='Rest1', stars=3, price=$}");
    }
}
