/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @DisplayName("TEST1")
    @Test void Test1() { // tester function
        App classUnderTest = new App(); // the class that contain the methode that you ment to test
       assertEquals(46, classUnderTest.fileJsTester("C:\\Users\\WAEL\\java-fundamentals\\linter\\resources\\gates.js"));
    }
@DisplayName("TEST2")
    @Test void Test2() {
        // tester function
        App classUnderTest = new App(); // the class that contain the methode that you ment to test
        assertEquals(0, classUnderTest.fileJsTester("C:\\Users\\WAEL\\java-fundamentals\\linter\\resources\\noErorr.js"));
    }

    @DisplayName("TEST3")
    @Test void Test3() {
        // tester function
        App classUnderTest = new App(); // the class that contain the methode that you ment to test
        assertEquals(2, classUnderTest.fileJsTester("C:\\Users\\WAEL\\java-fundamentals\\linter\\resources\\fewErorr.js"));
    }
    @Test void Test4() {
        // tester function
        App classUnderTest = new App(); // the class that contain the methode that you ment to test
        assertEquals(0, classUnderTest.fileJsTester("C:\\Users\\WAEL\\java-fundamentals\\linter\\resources\\Empyy.js"));
    }

    //   assertNotNull(exp ,act) : build in methode to comper avtuth value with expected  there alot of them
    // based on the type of output of the methode
    // classUnderTest.getGreeting() : the opject of class. the methde - the methode must retern value

}
